baseURL: https://upbeat-bohr-365e4c.netlify.com/
languageCode: en-us
title: GDG Accra
theme: hugo-fresh

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: GDG Accra.
    # Hero subtitle (optional)
    subtitle: A community built around Google Developer Technology - Android, Firebase, Flutter  & a lot more
    # Button text
    buttontext: Join Us
    # Where the main hero button links to
    buttonlink: "https://www.meetup.com/GDG-Accra/"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    - gdg
    - impact_hub
    - ispace
    - niit
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbarlogo:
    image: logos/gdgaccra.svg # Logo (from static/images/logos/)
    link: /

  navbar:
  - title: GDG
    url: /
  - title: WTM
    url: /
  - title: DevFest
    url: /
  - title: Shop
    url: /
    button: true

  section1:
    title: Great power comes
    subtitle: with great responsibility
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Free trial
    - title: Cloud integration
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"

  footer:
    # Logo (from /images/logos/___)
    logo: gdgaccra.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:

    - link: https://facebook.com/GDGAccra
      icon: facebook
    - link: https://twitter.com/GDGAccra
      icon: twitter

