baseURL: https://gdgaccra.appspot.com
languageCode: en-us
title: GDG Accra
theme: hugo-fresh

disableKinds:
- taxonomy
- taxonomyTerm

params:
  font:
    name: "Open Sans"
    sizes: [400, 600]
  hero:
    # Main hero title
    title: GDG Accra
    # Hero subtitle (optional)
    subtitle: an initiative to build a community in and around Accra to learn, share and get productive using the various Google products.
    # Button text
    buttontext: Become a member
    # Where the main hero button links to
    buttonlink: "https://www.meetup.com/GDG-Accra/"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
      - gdg
      - impact_hub
      - ispace
      - niit
      - wtm
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbarlogo:
    image: logos/gdgaccra.svg # Logo (from static/images/logos/)
    link: /

  navbar:
    - title: WTM
      url: /
    - title: DevFest
      url: /
    - title: Shop
      url: /


  section1:
    title: What we do?
    tiles:
      - title: Talks
        icon: talks
        text: Get updated with the latest news and announcement
        url: /
      - title: Code Labs
        icon: codelabs
        text: Get guidance from the community members
        url: /
      - title: Live Viewing Paries
        icon: live-viewing
        text: Share knowledge & Partake in Remote Events
        url: /

  section2:
    title: You're here because YOU want to belong
    subtitle: And we know it
    features:
      - title: Very Open Community
        text:  GDG prides itself on being an inclusive environment. Everyone and anyone interested in tech - from beginner developers to experienced professionals - are welcome to join
        # Icon (from /images/illustrations/icons/___.svg)
        icon: laptop-globe
      - title: Diverse Knowledge Base
        text: When you join a GDG, you’ll have the opportunity to meet local developers with similar interests in technology, attend talks on a wide range of technical topics, and learn new skills through hands-on workshops.
        icon: doc-sync
      - title: Shared Experience
        text: Growth through our mututal experiences. A support system that has your interest at heart.
        icon: mobile-feed


  footer:
    # Logo (from /images/logos/___)
    logo: gdgaccra.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
      - link: https://facebook.com/GDGAccra
        icon: facebook
      - link: https://twitter.com/GDGAccra
        icon: twitter
    quicklinks:
      column1:
        title: "About"
        links:
          - text: Google Developer Groups
            link: https://developers.google.com/programs/community/gdg/
          - text: WomenTechMakers
            link: https://www.womentechmakers.com/
          - text: Becoming a member
            link: https://www.meetup.com/GDG-Accra/

      column2:
          title: "Docs"
          links:
            - text: Code of Conduct Privacy & Policy
              link: https://docs.google.com/document/d/1Z48J188ZDFziWpByeeKwXCzJGeXt1wdTy6XtDfOS1_g/edit?usp=sharing
            - text: Terms & Conditions
              link: https://docs.google.com/document/d/1Gxg4ZJhRn6ZjHZ5qT11wwKhm7rYbfksrLMhoyd4y44s/edit?usp=sharing


